server:
  port: 8761   # ?????????????? 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # ???????
    register-with-eureka: false   # ????????????????? false????????????
    fetch-registry: false         # ?????????????????? false????????????
